[package]
name = "double-blind-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
double-blind.path = "../double-blind"
ssh-key = "0.6.7"
wasm-bindgen = "0.2.100"
